/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

/*
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
/*
};
*/



const sidebars = {
  mainSidebar: [
    {
      type: 'doc',
      label: 'Home', // sidebar label
      id: 'mainIndex', // document ID
    },
    {
      type: 'doc',
      label: 'Zond', // sidebar label
      id: 'zond-getting-started', // document ID
    },
    {
      type: 'doc',
      label: 'QRL', // sidebar label
      id: 'qrl-getting-started', // document ID
    },
  ],

  zondSidebar: [
    {
      type: 'doc',
      id: 'zond-getting-started', // document ID
      label: 'Getting Started', // sidebar label
    },
    {
      type: 'category',
      label: 'GZond',
      link: {
        type: 'generated-index',
        title: 'GZond Docs',
        description: 'Documentation for the GZond project.',
        slug: '/zond/gzond',
        keywords: ['gzond', 'zond', 'consensus'],
        image: '/assets/img/icons/yellow.png',
      },
      items: [
        'zond-getting-started',
      ]
    },
  ],




  qrlSidebar: [
    {
      type: 'doc',
      id: 'qrl-getting-started', // document ID
      label: 'Getting Started', // sidebar label
    },
    {
      type: 'doc',
      id: 'QRL/Learn/what-is-qrl', // document ID
      label: 'What Is The QRL', // sidebar label
    },    

    /////////////////////////////////
    // Using-QRL collapsible section
    /////////////////////////////////
    {
      type: 'category',
      label: 'Use The QRL',
      link: {
        type: 'generated-index',
        title: 'Using The QRL',
        description: 'Covering QRL Wallet usage, Node installation, Mining, and all things QRL Network Interfacing',
        slug: '/qrl/use',
        keywords: ['use'],
        image: '/assets/img/icons/yellow.png',
      },
      items: [
        { // Wallet section //
          type: 'category',
          label: 'Wallet',
          link: {
            type: 'generated-index',
            title: 'QRL Wallet',
            description: 'Covering QRL Wallets across all distributions and supported devices.',
            slug: '/qrl/use/wallet',
            keywords: ['use'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Use/Wallet/wallet-overview',
            'QRL/Use/Wallet/check-balance',
            'QRL/Use/Wallet/qrl-address-overview',
            { // web Wallet //
              type: 'category',
              label: 'Web Wallet',
              link: {
                type: 'generated-index',
                title: 'QRL Web Wallet',
                description: 'Covering the QRL Web Wallet usage.',
                slug: '/qrl/use/wallet/web',
                keywords: ['use-web-wallet'],
                image: '/assets/img/icons/yellow.png',
              },

              items: [
                'QRL/Use/Wallet/Web/web-wallet-overview',
                'QRL/Use/Wallet/Web/web-wallet-new',
                'QRL/Use/Wallet/Web/web-wallet-open',
                'QRL/Use/Wallet/Web/web-wallet-send',
                'QRL/Use/Wallet/Web/web-wallet-backup',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
            { // Desktop Wallet //
              type: 'category',
              label: 'Desktop Wallet',
              link: {
                type: 'generated-index',
                title: 'QRL Desktop Wallet',
                description: 'Covering the QRL Desktop Wallet usage.',
                slug: '/qrl/use/wallet/desktop',
                keywords: ['use-desktop-wallet'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Wallet/Desktop/desktop-wallet-overview',
                'QRL/Use/Wallet/Desktop/desktop-wallet-install',
                'QRL/Use/Wallet/Desktop/desktop-wallet-new',
                'QRL/Use/Wallet/Desktop/desktop-wallet-open',
                'QRL/Use/Wallet/Desktop/desktop-wallet-send',
                'QRL/Use/Wallet/Desktop/desktop-wallet-backup',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
            { // Ledger Wallet //
              type: 'category',
              label: 'Ledger Wallet',
              link: {
                type: 'generated-index',
                title: 'QRL Ledger Wallet',
                description: 'Covering the QRL Ledger device usage.',
                slug: '/qrl/use/wallet/ledger',
                keywords: ['use-ledger-wallet'],
                image: '/assets/img/icons/yellow.png',
              },

              items: [
                'QRL/Use/Wallet/Ledger/ledger-wallet-overview',
                'QRL/Use/Wallet/Ledger/ledger-wallet-new',
                'QRL/Use/Wallet/Ledger/ledger-wallet-open',
                'QRL/Use/Wallet/Ledger/ledger-wallet-send',
                'QRL/Use/Wallet/Ledger/ledger-wallet-backup-restore',
                'QRL/Use/Wallet/Ledger/ledger-wallet-plausible-deniability',
                'QRL/Use/Wallet/Ledger/ledger-wallet-known-issues',
                
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
            
            { // Mobile Wallet //
              type: 'category',
              label: 'Mobile Wallet',
              link: {
                type: 'generated-index',
                title: 'QRL Mobile Wallet',
                description: 'Covering the QRL mobile Wallet usage.',
                slug: '/qrl/use/wallet/mobile',
                keywords: ['use-mobile-wallet'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Wallet/Mobile/mobile-wallet-overview',
                'QRL/Use/Wallet/Mobile/mobile-wallet-new',
                'QRL/Use/Wallet/Mobile/mobile-wallet-open',
                'QRL/Use/Wallet/Mobile/mobile-wallet-backup',
                //'QRL/Use/Wallet/Mobile/mobile-wallet-send',
                //'QRL/Use/Wallet/Mobile/mobile-wallet-install',
                //'QRL/Use/Wallet/Mobile/mobile-wallet-switch-addresses',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
            
            { // offline Wallet //
              type: 'category',
              label: 'Offline Wallet',
              link: {
                type: 'generated-index',
                title: 'QRL Offline Wallet',
                description: 'Covering the QRL offline Wallet usage.',
                slug: '/qrl/use/wallet/offline',
                keywords: ['use-offline-wallet'],
                image: '/assets/img/icons/yellow.png',
              },              
              items: [
                'QRL/Use/Wallet/Offline/offline-wallet-overview',
                'QRL/Use/Wallet/Offline/offline-wallet-install',
                'QRL/Use/Wallet/Offline/offline-wallet-verify',
                'QRL/Use/Wallet/Offline/offline-wallet-new',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },

        { // Mining section //
          type: 'category',
          label: 'Mining',
          link: {
            type: 'generated-index',
            title: 'Mining QRL',
            description: 'Covering QRL Mining topics.',
            slug: '/qrl/use/mining',
            keywords: ['mining-qrl'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Use/Mining/mining-qrl-overview',
            'QRL/Use/Mining/solo-mining',
            'QRL/Use/Mining/pool-mining',
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },        

        { // Node section //
          type: 'category',
          label: 'Node',
          link: {
            type: 'generated-index',
            title: 'QRL Node',
            description: 'Covering QRL Node installation and operation.',
            slug: '/qrl/use/node',
            keywords: ['use-node'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Use/Node/overview',
            'QRL/Use/Node/node-requirements',
            'QRL/Use/Node/node-installation',
            'QRL/Use/Node/node-config',
            'QRL/Use/Node/node-uses',
            'QRL/Use/Node/node-update',
            'QRL/Use/Node/qrl-maintenance',

            { // node-cli section //
              type: 'category',
              label: 'Node-CLI',
              link: {
                type: 'generated-index',
                title: 'QRL Node-CLI',
                description: 'QRL node command line tools.',
                slug: '/qrl/use/node/node-cli',
                keywords: ['node-cli'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Node/node-cli/node-cli',
                'QRL/Use/Node/node-cli/backup-cli-wallet',
                'QRL/Use/Node/node-cli/node-cli-slave-xmss',
                ]
            },
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },
        { // Tools section //
          type: 'category',
          label: 'Tools',
          link: {
            type: 'generated-index',
            title: 'QRL Tools',
            description: 'Covering QRL Tools.',
            slug: '/qrl/use/tools',
            keywords: ['use-tool'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            // Tools Explorer
            {
              type: 'category',
              label: 'Explorer',
              link: {
                type: 'generated-index',
                title: 'QRL Explorer Usage',
                description: 'Using the QRL Explorer.',
                slug: '/qrl/use/tools/explorer',
                keywords: ['explorer'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Tools/explorer/qrl-explorer',
                'QRL/Use/Tools/explorer/address-lookup',
                'QRL/Use/Tools/explorer/transaction-lookup',
                'QRL/Use/Tools/explorer/block-lookup',
                'QRL/Use/Tools/explorer/token-lookup',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
            // Tools Messages
            {
              type: 'category',
              label: 'Messages',
              link: {
                type: 'generated-index',
                title: 'QRL Message Usage',
                description: 'QRL Message transaction usage',
                slug: '/qrl/use/tools/messages',
                keywords: ['messages'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Tools/messages/messages',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },

            // Tools multi-sig
            {
              type: 'category',
              label: 'Multisig',
              link: {
                type: 'generated-index',
                title: 'QRL Multi-signature Usage',
                description: 'Multi-sig transaction usage and guide.',
                slug: '/qrl/use/tools/multi-sig',
                keywords: ['multisig'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Tools/multisig/multisig',
                'QRL/Use/Tools/multisig/multisig-generate',
                'QRL/Use/Tools/multisig/Multisig-spend-proposal',
                'QRL/Use/Tools/multisig/multisig-vote',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },

            // Tools notarize
            {
              type: 'category',
              label: 'Notarize',
              link: {
                type: 'generated-index',
                title: 'Notarization Usage Guide',
                description: 'Usage for the Notarization functions.',
                slug: '/qrl/use/tools/notarize',
                keywords: ['notarize'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Tools/notarize/notarization-overview',
                'QRL/Use/Tools/notarize/notarization-data',
                'QRL/Use/Tools/notarize/notarization-verification',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },

            // Tools Tokens
            {
              type: 'category',
              label: 'Tokens',
              link: {
                type: 'generated-index',
                title: 'QRL Token Usage',
                description: 'Token Transactions and usage.',
                slug: '/qrl/use/tools/tokens',
                keywords: ['tokens'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Tools/tokens/qrl-tokens-overview',
                'QRL/Use/Tools/tokens/create-token',
                'QRL/Use/Tools/tokens/send-token',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
            {
              type: 'category',
              label: 'Integrations',
              link: {
                type: 'generated-index',
                title: 'QRL Integrations',
                description: 'QRL integrations with other projects.',
                slug: '/qrl/use/tools/integrations',
                keywords: ['integrations'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Tools/Integrations/keybase/keybase',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },

      ],
      collapsible: true, // Set the category to be collapsible
      collapsed: true, // Set the category to be initially collapsed or open by default
    },

    /////////////////////////////
    // Build On collapsible section
    /////////////////////////////
    {
      type: 'category',
      label: 'Build On QRL',
      link: {
        type: 'generated-index',
        title: 'Developer Docs',
        description: 'Advanced documentation for developers and adventurers building on the QRL.',
        slug: '/qrl/build',
        keywords: ['developer', 'build'],
        image: '/assets/img/icons/yellow.png',
      },
      items: [
        // 'Build/developers-overview',
        'QRL/Build/qrl-status',
        'QRL/Build/qrllib',
        'QRL/Build/security',
        'QRL/Build/Docker/qrl-docker',
        'QRL/Build/Mining/qrandomx',
        'QRL/Build/Mining/qrl-pool-setup',
        'QRL/Build/QIP/qip-overview',
        'QRL/Build/QRL-CLI/qrl-cli',
        'QRL/Build/qrl-private-network',
        { // Fundamentals//
          type: 'category',
          label: 'QRL Fundamentals',
          link: {
            type: 'generated-index',
            title: 'QRL Fundamental Topics',
            description: 'Covering some fundamental topics related to the QRL',
            slug: '/qrl/build/fundamentals',
            keywords: ['learn'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Build/Fundamentals/ots-keys',
            'QRL/Build/Fundamentals/whitepaper',
            'QRL/Build/Fundamentals/qrl-emission',
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },
        { // Message Encoding//
          type: 'category',
          label: 'QRL Messages',
          link: {
            type: 'generated-index',
            title: 'QRL Message Encoding Documentation',
            description: 'Message encoding standard for the various QRL Message Transaction types',
            slug: '/qrl/build/messages',
            keywords: ['learn'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Build/Messages/message-tx-encoding',
            'QRL/Build/Messages/notarization-message-encoding',
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },
        { // Address Scheme//
          type: 'category',
          label: 'QRL Addresses',
          link: {
            type: 'generated-index',
            title: 'QRL Address Docs',
            description: 'Building blocks for the QRL Address Scheme, how addresses are constructed and the cryptography behind them',
            slug: '/qrl/build/addresses',
            keywords: ['learn'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Build/Address/qrl-address-scheme',
            'QRL/Build/Address/hexphrase',
            'QRL/Build/Address/mnemonic',
            'QRL/Build/Address/wallet-json',
            'QRL/Build/Address/slave-keys',
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },
        { // QRL Node CLI //
          type: 'category',
          label: 'QRL Helpers',
          link: {
            type: 'generated-index',
            title: 'QRL Code Libraries and helpers',
            description: 'Various helper scripts developed to aid and assist in developing on the QRL.',
            slug: '/qrl/build/helpers',
            keywords: ['qrl-helpers', 'node-helpers'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Build/QRL-Helpers/node-helpers',
            'QRL/Build/QRL-Helpers/validate-qrl-address',
            'QRL/Build/QRL-Helpers/explorer-helpers',
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },
      ],
      collapsible: true, // Set the category to be collapsible
      collapsed: true, // Set the category to be initially collapsed or open by default
    },

    /////////////////////////////
    // API collapsible section
    /////////////////////////////
    {
      type: 'category',
      label: 'QRL API',
      link: {
        type: 'generated-index',
        title: 'API Docs',
        description: 'API documentation for developers building on the QRL.',
        slug: '/qrl/api',
        keywords: ['api', 'developers', 'rest', 'grpc'],
        image: '/assets/img/icons/yellow.png',
      },
      items: [
        'QRL/API/qrl-api-overview',
        'QRL/API/qrl-public-api',
        'QRL/API/wallet-api',
        'QRL/API/explorer-api',
        'QRL/API/richlist-api',
        'QRL/API/walletd-rest-proxy',
        'QRL/API/zeus-proxy',
      ]
    },

  ],

  // tutorialSidebar shown on the tutorials pages
  tutorialSidebar: [
    'QRL/Tutorials/qrl-tutorials',
    'QRL/Tutorials/notarize-qrl-cli',

    { // Node tutorials //
      type: 'category',
      label: 'Node',
      link: {
        type: 'generated-index',
        title: 'QRL Node Tutorials',
        description: 'Guides related to node operations.',
        slug: '/qrl/tutorials/node',
        keywords: ['node-tutorials'],
        image: '/assets/img/icons/yellow.png',
      },

      items: [
        'QRL/Tutorials/Node/dual-node-host',
        'QRL/Tutorials/Node/walletd-api-linux-guide',
        'QRL/Tutorials/Node/backup-restore-node-state',
      ],
      collapsible: true, // Set the category to be collapsible
      collapsed: true, // Set the category to be initially collapsed or open by default
    },

    { // Node tutorials //
      type: 'category',
      label: 'Wallet',
      link: {
        type: 'generated-index',
        title: 'QRL Wallet Tutorials',
        description: 'Guides related to wallet operations.',
        slug: '/qrl/tutorials/wallet',
        keywords: ['wallet-tutorials'],
        image: '/assets/img/icons/yellow.png',
      },

      items: [
      // 'Tutorials/Wallet/automatic-wallet-api-use', 
      // 'Tutorials/Wallet/automatic-wallet-api', 
      'QRL/Tutorials/Wallet/generate-address-dice',
      ],
      collapsible: true, // Set the category to be collapsible
      collapsed: true, // Set the category to be initially collapsed or open by default
    },
  ],
};


export default sidebars;
