// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */


const bottomSidebar = [
    {
      type: 'html',
      value: '<hr />', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'ref', 
      id: 'mainIndex', 
      label: 'Home'
    },
    {
      type: 'ref', 
      id: 'ZOND/User/index', 
      label: 'User Docs'
    },
    {
      type: 'ref', 
      id: 'ZOND/Gzond/go-zond-index', 
      label: 'Gzond Docs'
    },
    {
      type: 'ref', 
      id: 'ZOND/Qrysm/qrysm-getting-started', 
      label: 'Qrysm Docs'
    },
  ];

const sidebars = {

// Main sidebar served on the home page //
  mainSidebar: [
    {
      type: 'ref', 
      id: 'mainIndex', 
      label: 'Home'
    },
    // Zond Category drop down //
    {
      type: 'category',
      label: 'Zond',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'ref', id: 'zond-getting-started'},
        {
          type: 'category',
          label: 'Zond Betanet',
          items: [
            {type: 'autogenerated', dirName: 'ZOND/Test'},
          ],
        },
        {
          type: 'category',
          label: 'User Documentation',
          items: [
            {type: 'autogenerated', dirName: 'ZOND/User'},
          ],
        },
        {
          type: 'category',
          label: 'Gzond',
          items: [
            {type: 'autogenerated', dirName: 'ZOND/Gzond'},
          ],
        },
        {
          type: 'category',
          label: 'Qrysm',
          items: [
            {type: 'autogenerated', dirName: 'ZOND/Qrysm'},
          ],
        },
      ],
    },
    // QRL Category drop down //
    {
      type: 'category',
      label: 'QRL',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'qrl-getting-started', // document ID
          label: 'Getting Started'
        },
        'QRL/Learn/what-is-qrl',
        {
          type: 'category',
          label: 'Using QRL',
          items: [
            {type: 'autogenerated', dirName: 'QRL/Use'},
          ],
        },
        {
          type: 'category',
          label: 'Develop QRL',
          items: [
            {type: 'autogenerated', dirName: 'QRL/Build'},
          ],
        },
        {
          type: 'category',
          label: 'QRL API\'s',
          items: [
            {type: 'autogenerated', dirName: 'QRL/API'},
          ],
        },
      ],
    },
  ],

  // Test-Zond pages //
  betaSidebar: [
    // displayed in all of the test-zond pages
    // auto-generated from directory listed below //
    
    {
      type: 'html',
      value: 'Zond Betanet',
      className: 'sidebar-title',
    },
    {
      type: 'autogenerated', 
      dirName: 'ZOND/Test'
    },

    // Seperator and bottom content //
    bottomSidebar,
  ],

  // gzond docs //
  gzondSidebar: [
    {
      type: 'html',
      value: 'Gzond Docs',
      className: 'sidebar-title',
    },
    {
      type: 'autogenerated', 
      dirName: 'ZOND/Gzond'
    },


    // Seperator and bottom content //
    bottomSidebar,

  ],

  // QRL Sidebar //
  qrlSidebar: [

    {
      type: 'html',
      value: '<a href="../"><button type="button" class="clean-btn navbar-sidebar__back">← Back Home</button></a>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },

    {
      type: 'doc',
      id: 'qrl-getting-started', // document ID
      label: 'Getting Started', // sidebar label
    },
    {
      type: 'doc',
      id: 'QRL/Learn/what-is-qrl', // document ID
      label: 'What Is The QRL', // sidebar label
    },    

    /////////////////////////////////
    // Using-QRL collapsible section
    /////////////////////////////////
    {
      type: 'category',
      label: 'Use The QRL',
      link: {
        type: 'generated-index',
        title: 'Using The QRL',
        description: 'Covering QRL Wallet usage, Node installation, Mining, and all things QRL Network Interfacing',
        slug: '/qrl/use',
        keywords: ['use'],
        image: '/assets/img/icons/yellow.png',
      },
      items: [
        { // Wallet section //
          type: 'category',
          label: 'Wallet',
          link: {
            type: 'generated-index',
            title: 'QRL Wallet',
            description: 'Covering QRL Wallets across all distributions and supported devices.',
            slug: '/qrl/use/wallet',
            keywords: ['use'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Use/Wallet/wallet-overview',
            'QRL/Use/Wallet/check-balance',
            'QRL/Use/Wallet/qrl-address-overview',
            { // web Wallet //
              type: 'category',
              label: 'Web Wallet',
              link: {
                type: 'generated-index',
                title: 'QRL Web Wallet',
                description: 'Covering the QRL Web Wallet usage.',
                slug: '/qrl/use/wallet/web',
                keywords: ['use-web-wallet'],
                image: '/assets/img/icons/yellow.png',
              },

              items: [
                'QRL/Use/Wallet/Web/web-wallet-overview',
                'QRL/Use/Wallet/Web/web-wallet-new',
                'QRL/Use/Wallet/Web/web-wallet-open',
                'QRL/Use/Wallet/Web/web-wallet-send',
                'QRL/Use/Wallet/Web/web-wallet-backup',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
            { // Desktop Wallet //
              type: 'category',
              label: 'Desktop Wallet',
              link: {
                type: 'generated-index',
                title: 'QRL Desktop Wallet',
                description: 'Covering the QRL Desktop Wallet usage.',
                slug: '/qrl/use/wallet/desktop',
                keywords: ['use-desktop-wallet'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Wallet/Desktop/desktop-wallet-overview',
                'QRL/Use/Wallet/Desktop/desktop-wallet-install',
                'QRL/Use/Wallet/Desktop/desktop-wallet-new',
                'QRL/Use/Wallet/Desktop/desktop-wallet-open',
                'QRL/Use/Wallet/Desktop/desktop-wallet-send',
                'QRL/Use/Wallet/Desktop/desktop-wallet-backup',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
            { // Ledger Wallet //
              type: 'category',
              label: 'Ledger Wallet',
              link: {
                type: 'generated-index',
                title: 'QRL Ledger Wallet',
                description: 'Covering the QRL Ledger device usage.',
                slug: '/qrl/use/wallet/ledger',
                keywords: ['use-ledger-wallet'],
                image: '/assets/img/icons/yellow.png',
              },

              items: [
                'QRL/Use/Wallet/Ledger/ledger-wallet-overview',
                'QRL/Use/Wallet/Ledger/ledger-wallet-new',
                'QRL/Use/Wallet/Ledger/ledger-wallet-open',
                'QRL/Use/Wallet/Ledger/ledger-wallet-send',
                'QRL/Use/Wallet/Ledger/ledger-wallet-backup-restore',
                'QRL/Use/Wallet/Ledger/ledger-wallet-plausible-deniability',
                'QRL/Use/Wallet/Ledger/ledger-wallet-known-issues',
                
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
            
            { // Mobile Wallet //
              type: 'category',
              label: 'Mobile Wallet',
              link: {
                type: 'generated-index',
                title: 'QRL Mobile Wallet',
                description: 'Covering the QRL mobile Wallet usage.',
                slug: '/qrl/use/wallet/mobile',
                keywords: ['use-mobile-wallet'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Wallet/Mobile/mobile-wallet-overview',
                'QRL/Use/Wallet/Mobile/mobile-wallet-new',
                'QRL/Use/Wallet/Mobile/mobile-wallet-open',
                'QRL/Use/Wallet/Mobile/mobile-wallet-backup',
                //'QRL/Use/Wallet/Mobile/mobile-wallet-send',
                //'QRL/Use/Wallet/Mobile/mobile-wallet-install',
                //'QRL/Use/Wallet/Mobile/mobile-wallet-switch-addresses',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
            
            { // offline Wallet //
              type: 'category',
              label: 'Offline Wallet',
              link: {
                type: 'generated-index',
                title: 'QRL Offline Wallet',
                description: 'Covering the QRL offline Wallet usage.',
                slug: '/qrl/use/wallet/offline',
                keywords: ['use-offline-wallet'],
                image: '/assets/img/icons/yellow.png',
              },              
              items: [
                'QRL/Use/Wallet/Offline/offline-wallet-overview',
                'QRL/Use/Wallet/Offline/offline-wallet-install',
                'QRL/Use/Wallet/Offline/offline-wallet-verify',
                'QRL/Use/Wallet/Offline/offline-wallet-new',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },

        { // Mining section //
          type: 'category',
          label: 'Mining',
          link: {
            type: 'generated-index',
            title: 'Mining QRL',
            description: 'Covering QRL Mining topics.',
            slug: '/qrl/use/mining',
            keywords: ['mining-qrl'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Use/Mining/mining-qrl-overview',
            'QRL/Use/Mining/solo-mining',
            'QRL/Use/Mining/pool-mining',
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },        

        { // Node section //
          type: 'category',
          label: 'Node',
          link: {
            type: 'generated-index',
            title: 'QRL Node',
            description: 'Covering QRL Node installation and operation.',
            slug: '/qrl/use/node',
            keywords: ['use-node'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Use/Node/overview',
            'QRL/Use/Node/node-requirements',
            'QRL/Use/Node/node-installation',
            'QRL/Use/Node/node-config',
            'QRL/Use/Node/node-uses',
            'QRL/Use/Node/node-update',
            'QRL/Use/Node/qrl-maintenance',

            { // node-cli section //
              type: 'category',
              label: 'Node-CLI',
              link: {
                type: 'generated-index',
                title: 'QRL Node-CLI',
                description: 'QRL node command line tools.',
                slug: '/qrl/use/node/node-cli',
                keywords: ['node-cli'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Node/node-cli/node-cli',
                'QRL/Use/Node/node-cli/backup-cli-wallet',
                'QRL/Use/Node/node-cli/node-cli-slave-xmss',
                ]
            },
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },
        { // Tools section //
          type: 'category',
          label: 'Tools',
          link: {
            type: 'generated-index',
            title: 'QRL Tools',
            description: 'Covering QRL Tools.',
            slug: '/qrl/use/tools',
            keywords: ['use-tool'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            // Tools Explorer
            {
              type: 'category',
              label: 'Explorer',
              link: {
                type: 'generated-index',
                title: 'QRL Explorer Usage',
                description: 'Using the QRL Explorer.',
                slug: '/qrl/use/tools/explorer',
                keywords: ['explorer'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Tools/explorer/qrl-explorer',
                'QRL/Use/Tools/explorer/address-lookup',
                'QRL/Use/Tools/explorer/transaction-lookup',
                'QRL/Use/Tools/explorer/block-lookup',
                'QRL/Use/Tools/explorer/token-lookup',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
            // Tools Messages
            {
              type: 'category',
              label: 'Messages',
              link: {
                type: 'generated-index',
                title: 'QRL Message Usage',
                description: 'QRL Message transaction usage',
                slug: '/qrl/use/tools/messages',
                keywords: ['messages'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Tools/messages/messages',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },

            // Tools multi-sig
            {
              type: 'category',
              label: 'Multisig',
              link: {
                type: 'generated-index',
                title: 'QRL Multi-signature Usage',
                description: 'Multi-sig transaction usage and guide.',
                slug: '/qrl/use/tools/multi-sig',
                keywords: ['multisig'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Tools/multisig/multisig',
                'QRL/Use/Tools/multisig/multisig-generate',
                'QRL/Use/Tools/multisig/Multisig-spend-proposal',
                'QRL/Use/Tools/multisig/multisig-vote',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },

            // Tools notarize
            {
              type: 'category',
              label: 'Notarize',
              link: {
                type: 'generated-index',
                title: 'Notarization Usage Guide',
                description: 'Usage for the Notarization functions.',
                slug: '/qrl/use/tools/notarize',
                keywords: ['notarize'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Tools/notarize/notarization-overview',
                'QRL/Use/Tools/notarize/notarization-data',
                'QRL/Use/Tools/notarize/notarization-verification',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },

            // Tools Tokens
            {
              type: 'category',
              label: 'Tokens',
              link: {
                type: 'generated-index',
                title: 'QRL Token Usage',
                description: 'Token Transactions and usage.',
                slug: '/qrl/use/tools/tokens',
                keywords: ['tokens'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Tools/tokens/qrl-tokens-overview',
                'QRL/Use/Tools/tokens/create-token',
                'QRL/Use/Tools/tokens/send-token',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
            {
              type: 'category',
              label: 'Integrations',
              link: {
                type: 'generated-index',
                title: 'QRL Integrations',
                description: 'QRL integrations with other projects.',
                slug: '/qrl/use/tools/integrations',
                keywords: ['integrations'],
                image: '/assets/img/icons/yellow.png',
              },
              items: [
                'QRL/Use/Tools/Integrations/keybase/keybase',
              ],
              collapsible: true, // Set the category to be collapsible
              collapsed: true, // Set the category to be initially collapsed or open by default
            },
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },

      ],
      collapsible: true, // Set the category to be collapsible
      collapsed: true, // Set the category to be initially collapsed or open by default
    },

    /////////////////////////////
    // Build On collapsible section
    /////////////////////////////
    {
      type: 'category',
      label: 'Build On QRL',
      link: {
        type: 'generated-index',
        title: 'Developer Docs',
        description: 'Advanced documentation for developers and adventurers building on the QRL.',
        slug: '/qrl/build',
        keywords: ['developer', 'build'],
        image: '/assets/img/icons/yellow.png',
      },
      items: [
        // 'Build/developers-overview',
        'QRL/Build/qrl-status',
        'QRL/Build/qrllib',
        'QRL/Build/security',
        'QRL/Build/Docker/qrl-docker',
        'QRL/Build/Mining/qrandomx',
        'QRL/Build/Mining/qrl-pool-setup',
        'QRL/Build/QIP/qip-overview',
        'QRL/Build/QRL-CLI/qrl-cli',
        'QRL/Build/qrl-private-network',
        { // Fundamentals//
          type: 'category',
          label: 'QRL Fundamentals',
          link: {
            type: 'generated-index',
            title: 'QRL Fundamental Topics',
            description: 'Covering some fundamental topics related to the QRL',
            slug: '/qrl/build/fundamentals',
            keywords: ['learn'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Build/Fundamentals/ots-keys',
            'QRL/Build/Fundamentals/whitepaper',
            'QRL/Build/Fundamentals/qrl-emission',
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },
        { // Message Encoding//
          type: 'category',
          label: 'QRL Messages',
          link: {
            type: 'generated-index',
            title: 'QRL Message Encoding Documentation',
            description: 'Message encoding standard for the various QRL Message Transaction types',
            slug: '/qrl/build/messages',
            keywords: ['learn'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Build/Messages/message-tx-encoding',
            'QRL/Build/Messages/notarization-message-encoding',
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },
        { // Address Scheme//
          type: 'category',
          label: 'QRL Addresses',
          link: {
            type: 'generated-index',
            title: 'QRL Address Docs',
            description: 'Building blocks for the QRL Address Scheme, how addresses are constructed and the cryptography behind them',
            slug: '/qrl/build/addresses',
            keywords: ['learn'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Build/Address/qrl-address-scheme',
            'QRL/Build/Address/hexphrase',
            'QRL/Build/Address/mnemonic',
            'QRL/Build/Address/wallet-json',
            'QRL/Build/Address/slave-keys',
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },
        { // QRL Node CLI //
          type: 'category',
          label: 'QRL Helpers',
          link: {
            type: 'generated-index',
            title: 'QRL Code Libraries and helpers',
            description: 'Various helper scripts developed to aid and assist in developing on the QRL.',
            slug: '/qrl/build/helpers',
            keywords: ['qrl-helpers', 'node-helpers'],
            image: '/assets/img/icons/yellow.png',
          },
          items: [
            'QRL/Build/QRL-Helpers/node-helpers',
            'QRL/Build/QRL-Helpers/validate-qrl-address',
            'QRL/Build/QRL-Helpers/explorer-helpers',
          ],
          collapsible: true, // Set the category to be collapsible
          collapsed: true, // Set the category to be initially collapsed or open by default
        },
      ],
      collapsible: true, // Set the category to be collapsible
      collapsed: true, // Set the category to be initially collapsed or open by default
    },

    /////////////////////////////
    // API collapsible section
    /////////////////////////////
    {
      type: 'category',
      label: 'QRL API',
      link: {
        type: 'generated-index',
        title: 'API Docs',
        description: 'API documentation for developers building on the QRL.',
        slug: '/qrl/api',
        keywords: ['api', 'developers', 'rest', 'grpc'],
        image: '/assets/img/icons/yellow.png',
      },
      items: [
        'QRL/API/qrl-api-overview',
        'QRL/API/qrl-public-api',
        'QRL/API/wallet-api',
        'QRL/API/explorer-api',
        'QRL/API/richlist-api',
        'QRL/API/walletd-rest-proxy',
        'QRL/API/zeus-proxy',
      ]
    },
  ],

  // QRL tutorialSidebar shown on the tutorials pages
  tutorialSidebar: [
    'QRL/Tutorials/qrl-tutorials',
    'QRL/Tutorials/notarize-qrl-cli',

    { // Node tutorials //
      type: 'category',
      label: 'Node',
      link: {
        type: 'generated-index',
        title: 'QRL Node Tutorials',
        description: 'Guides related to node operations.',
        slug: '/qrl/tutorials/node',
        keywords: ['node-tutorials'],
        image: '/assets/img/icons/yellow.png',
      },

      items: [
        'QRL/Tutorials/Node/dual-node-host',
        'QRL/Tutorials/Node/walletd-api-linux-guide',
        'QRL/Tutorials/Node/backup-restore-node-state',
      ],
      collapsible: true, // Set the category to be collapsible
      collapsed: true, // Set the category to be initially collapsed or open by default
    },

    { // Node tutorials //
      type: 'category',
      label: 'Wallet',
      link: {
        type: 'generated-index',
        title: 'QRL Wallet Tutorials',
        description: 'Guides related to wallet operations.',
        slug: '/qrl/tutorials/wallet',
        keywords: ['wallet-tutorials'],
        image: '/assets/img/icons/yellow.png',
      },

      items: [
      // 'Tutorials/Wallet/automatic-wallet-api-use', 
      // 'Tutorials/Wallet/automatic-wallet-api', 
      'QRL/Tutorials/Wallet/generate-address-dice',
      ],
      collapsible: true, // Set the category to be collapsible
      collapsed: true, // Set the category to be initially collapsed or open by default
    },
    bottomSidebar,
  ],




  // Qrysm pages //
  qrysmSidebar: [

    {
      "type": "doc",
      "id": "ZOND/Qrysm/qrysm-getting-started"
    },
    
    {
      "type": "doc",
      "id": "ZOND/Qrysm/install/install-with-script"
    },
    {
      "type": "doc",
      "id": "ZOND/Qrysm/wallet/withdraw-validator"
    },
    {
      "type": "doc",
      "id": "ZOND/Qrysm/security-best-practices"
    },
    {
      "type": "doc",
      "id": "ZOND/Qrysm/qrysm-usage/parameters"
    },
    {
      "type": "doc",
      "id": "ZOND/Qrysm/monitoring/checking-status"
    },
    {
      "type": "doc",
      "id": "ZOND/Qrysm/troubleshooting/issues-errors"
    },
    {
      "type": "category",
      "collapsed": true,
      "collapsible": true,
      "label": "Advanced installation guides",
      "items": [
        {
          "type": "doc",
          "id": "ZOND/Qrysm/install/install-with-docker"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/install/install-with-bazel"
        }
      ]
    },
    {
      "type": "category",
      "collapsed": true,
      "collapsible": true,
      "label": "How-tos",
      "items": [
        {
          "type": "doc",
          "id": "ZOND/Qrysm/execution-node/fee-recipient"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/execution-node/authentication"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/execution-node/configuring-for-qrysm"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/advanced/builder"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/qrysm-usage/qrysmctl"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/qrysm-usage/staying-up-to-date"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/qrysm-usage/checkpoint-sync"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/qrysm-usage/slasher"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/advanced/beacon_node_api"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/advanced/proof-of-stake-devnet"
        },
        {
          "type": "category",
          "collapsed": true,
          "collapsible": true,
          "label": "Backups and migrations",
          "items": [
            {
              "type": "doc",
              "id": "ZOND/Qrysm/qrysm-usage/database-backups"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/wallet/slashing-protection"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/advanced/migrating-keys"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/advanced/switch-clients"
            }
          ]
        },
        {
          "type": "category",
          "collapsed": true,
          "collapsible": true,
          "label": "Validator and wallet management",
          "items": [
            {
              "type": "doc",
              "id": "ZOND/Qrysm/wallet/deterministic"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/wallet/nondeterministic"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/advanced/maintaining-uptime"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/wallet/web3signer"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/qrysm-usage/graffiti-file"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/wallet/exiting-a-validator"
            },
            {
                "type": "doc",
                "id": "ZOND/Qrysm/wallet/withdraw-validator"
            }
          ]
        },
        {
          "type": "category",
          "collapsed": true,
          "collapsible": true,
          "label": "Monitoring, metrics, and alerts",
          "items": [
            {
              "type": "doc",
              "id": "ZOND/Qrysm/monitoring/is-everything-fine"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/qrysm-usage/individual-validator-monitoring"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/qrysm-usage/monitoring/grafana-dashboard"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/qrysm-usage/client-stats"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/qrysm-usage/web-interface"
            }
          ]
        },
        {
          "type": "category",
          "collapsed": true,
          "collapsible": true,
          "label": "Managing connections",
          "items": [
            {
              "type": "doc",
              "id": "ZOND/Qrysm/qrysm-usage/secure-grpc"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/qrysm-usage/p2p-host-ip"
            }
          ]
        }
      ]
    },
    {
      "type": "category",
      "collapsed": true,
      "collapsible": true,
      "label": "Concepts",
      "items": [
        {
          "type": "doc",
          "id": "ZOND/Qrysm/concepts/nodes-networks"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/how-qrysm-works/validator-lifecycle"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/wallet/introduction"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/concepts/slashing"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/concepts/blobs"
        }
      ]
    },
    {
      "type": "category",
      "collapsed": true,
      "collapsible": true,
      "label": "Developer wiki",
      "items": [
        {
          "type": "doc",
          "id": "ZOND/Qrysm/contribute/contribution-guidelines"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/contribute/golang-principles"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/reading/golang"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/reading/bazel"
        },
        {
          "type": "category",
          "collapsed": true,
          "collapsible": true,
          "label": "APIs",
          "items": [
            {
              "type": "doc",
              "id": "ZOND/Qrysm/how-qrysm-works/ethereum-public-api"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/how-qrysm-works/qrysm-public-api"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/how-qrysm-works/keymanager-api"
            }
          ]
        },
        {
          "type": "category",
          "collapsed": true,
          "collapsible": true,
          "label": "Developer concepts",
          "items": [
            {
              "type": "doc",
              "id": "ZOND/Qrysm/devtools/init-state"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/devtools/net-design"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/how-qrysm-works/architecture-overview"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/how-qrysm-works/beacon-node"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/how-qrysm-works/qrysm-validator-client"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/how-qrysm-works/optimistic-sync"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/how-qrysm-works/validator-deposit-contract"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/how-qrysm-works/database-backend-boltdb"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/how-qrysm-works/p2p-networking"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/how-qrysm-works/bls-cryptography"
            },
            {
              "type": "doc",
              "id": "ZOND/Qrysm/devtools/end-to-end"
            }
          ]
        }
      ]
    },
    {
      "type": "category",
      "collapsed": true,
      "collapsible": true,
      "label": "Misc",
      "items": [
        {
          "type": "doc",
          "id": "ZOND/Qrysm/audits/phase0"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/licenses/prysmatic-labs"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/reading/eth2"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/reading/testnet-postmortems"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/devtools/block-explorers"
        },
        {
          "type": "doc",
          "id": "ZOND/Qrysm/contribute/bugreports"
        }
      ]
    },
    {
      "type": "doc",
      "id": "ZOND/Qrysm/faq"
    },
    {
      "type": "doc",
      "id": "ZOND/Qrysm/terminology"
    },
  


    // Seperator and bottom content //
    bottomSidebar,

  ],





  // zond sidebar //
  zondSidebar: [
    {
      type: 'html',
      value: '<a href="../"><button type="button" class="clean-btn navbar-sidebar__back">← Back Home</button></a>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },

    {
      type: 'doc',
      id: 'zond-getting-started', // document ID
      label: 'Getting Started', // sidebar label
    },
    bottomSidebar,
  ],







};


export default sidebars;
